#!/bin/sh
# -------
# File:        eclipse-cdt-neon
# Description: Download and extracts archived p2 repo of eclpise CDT for future use
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

usage(){
	echo "$(basename "$0") {install|uninstall}" >&2
	exit 1
}

[ "$1" ] || usage

DEST_DIR="/opt/eclipse-neon-1rc3/cdt"
REQ_URL="http://mirror.netcologne.de/eclipse//tools/cdt/releases/9.0/cdt-9.0.1.zip"

case "$1" in
	install)
		if aurex-cache get "$REQ_URL" ; then
			EXEC_FILE="$(aurex-cache file "$REQ_URL")"
			if [ "$EXEC_FILE" ] && [ -r "$EXEC_FILE" ] ; then
				echo "Extracting files"
				mkdir -p "$DEST_DIR"
				unzip -q -o -d "$DEST_DIR"  "$EXEC_FILE"
			fi
		fi
		;;
	uninstall)
		rm -fr "$DEST_DIR"

		;;
	*)
		usage
		;;
esac

exit 0
